version: '3'
services:
  # es:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
  #   container_name: es
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9200:9200
  #   volumes:
  #     - esdata1:/usr/share/elasticsearch/data
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - discovery.type=single-node
    ports:
      - 27017:27017

  wallabot:
    build: ./wallabot
    # image: magicjf/walla5:latest
    container_name: wallabot
    environment:
      - DEBUG=True
    depends_on:
      - mongo

  # scrapy:
  #   image: magicjf/scraper
  #   container_name: scrapy
  #   environment:
  #     - discovery.type=single-node
  #   command:
  #     [
  #       'python3',
  #       './launcher.py',
  #       "{ 'spider_name': 'header_spider', 'spider_kwargs': { 'start_urls': ['https://lavanguardia.com'] }}",
  #     ]
  #   depends_on:
  #     - mongo

  fargatescraper:
    build: ./FargateScraper
    container_name: fargate
    environment:
      - discovery.type=single-node
    command:
      [
        'python3',
        './launcher.py',
        "{ 'spider_name': 'header_spider', 'spider_kwargs': { 'start_urls': ['https://lavanguardia.com'] }}",
      ]
    depends_on:
      - mongo

  # foodtrucksweb:
  #   build: .
  #   container_name: foodtrucksweb
  #   command: python3 app.py
  #   environment:
  #     - DEBUG=True
  #   depends_on:
  #     - es
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - ./flask-app:/opt/flask-app
volumes:
  esdata1:
    driver: local
